### ISSUE TITLE
Support for service in Frankfort

### ISSUE THREAD

**Issue by PhilippeComte** [IBM/nlc-icd10-classifier#38]
To support a NLC instance in Frankfurt with apikey:
 
- I've added a line in the .env file and commented the password line
NATURAL_LANGUAGE_CLASSIFIER_USERNAME=apikey
/#/ NATURAL_LANGUAGE_CLASSIFIER_PASSWORD=<add_NLC_password>
NATURAL_LANGUAGE_CLASSIFIER_IAM_APIKEY='xxxxxxxxx....xxx'
**NATURAL_LANGUAGE_CLASSIFIER_URL='https://gateway-fra.watsonplatform.net/natural-language-classifier/api'**

- I've modified the welcome.py file (the line with  the url)
<img width="748" alt="image" src="https://user-images.githubusercontent.com/7049461/52180582-80e68e00-27e8-11e9-8de7-31307386fc7d.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/7049461/52180602-b4c1b380-27e8-11e9-90bb-a7dbe03bbda2.png">

and
<img width="683" alt="image" src="https://user-images.githubusercontent.com/7049461/52180613-dc188080-27e8-11e9-8079-959f6af22e94.png">

Not sure it's enough, but at least my credentials are recognised .
As the model is not trained yet , I still have an error : 
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/7049461/52180647-39143680-27e9-11e9-820e-5df2b7cf472b.png">

**Comment by PhilippeComte** [comment]
Hi Thank you ! 
I'll be patient !

**Comment by stevemart** [comment]
@PhilippeComte Is this still an issue for you?

**Comment by PhilippeComte** [comment]
No. Thanks for your help .
