### ISSUE TITLE
trouble getting started with watson nlc

### ISSUE THREAD

**Issue by proCoder02** [IBM/nlc-icd10-classifier#39]
mytestenv) (base) C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier>curl -i -u "apikey:###############################################
![cass2](https://user-images.githubusercontent.com/21214465/52786571-3cc57a00-3081-11e9-9b20-35649af5c2c4.PNG)
" ^
More? -F training_data=C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier\data\ICD-10-GT-AA.csv ^
More? -F training_metadata="{\"language\":\"en\",\"name\":\"ICD_classifier\"}" ^
More? "https://gateway-fra.watsonplatform.net/natural-language-classifier/api/v1/classifiers"
HTTP/1.1 400 Bad Request
X-Backside-Transport: FAIL FAIL
Content-Type: application/json
X-XSS-Protection: 1
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store
Pragma: no-cache
Expires: 0
x-global-transaction-id: 0e7fa6da5c655d2728bf7de9
X-DP-Watson-Tran-ID: gateway-fra-dp02-683638249
X-DP-Transit-ID: gateway-fra-dp02-683638249
Strict-Transport-Security: max-age=31536000;
Content-Length: 121
Date: Thu, 14 Feb 2019 12:20:56 GMT
Connection: close

{
  "code" : 400,
  "error" : "Malformed data",
  "description" : "The 'class' value at line 1 and column 1 is 'null'."
}
(mytestenv) (base) C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier>

this is the error i am getting after following each step in github repo for IBM Watson nlc/icd10

kindly respond.Its urgent

**Comment by scottdangelo** [comment]
One problem I see is that the NLC API requires that the file input use this syntax:
```
training_data=@$FILE
```
With the '@' sign being required, between the '=' and the file name.
I'm not sure if there is any issue with the multi-line input, but the line ending '^' and the 'More?' might also be having an effect.

**Comment by stevemart** [comment]
@proCoder02 the `@` sign is definitely required in your training_data argument

``
training_data=@C:\...
``` 

From the [curl docs](https://curl.haxx.se/docs/manpage.html):

> @filename
> This will make curl load data from the given file (including any newlines), URL-encode that data and pass it on in the POST.

**Comment by proCoder02** [comment]
Thanks a lot!!! that error was resolved but i ended up having another error :(



(mytestenv) (base) C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier>curl -i -u "apikey:############################################################" -F training_data=@C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier\data\ICD-10-GT-AA.csv -F training_metadata="{\"language\":\"en\",\"name\":\"ICD_classifier\"}" "https://gateway-fra.watsonplatform.net/natural-language-classifier/api"
HTTP/1.1 100 Continue
X-Note: Gateway Ack

HTTP/1.1 404 Not Found
X-Backside-Transport: FAIL FAIL
Content-Type: application/json
X-DP-Transit-ID: gateway-fra-dp01-498873897
X-Global-Transaction-ID: 683fc2df5c6656fa1dbc3629
Strict-Transport-Security: max-age=31536000;
X-DP-Watson-Tran-ID: gateway-fra-dp01-498873897
Content-Length: 34
Date: Fri, 15 Feb 2019 06:06:52 GMT
Connection: close

{"code":404, "error": "Not Found"}

**Comment by scottdangelo** [comment]
See the [api docs](https://cloud.ibm.com/apidocs/natural-language-classifier#create-classifier)
I think you need curly brackets around your api key:
`"apikey:{apikey}"`
Also, it looks like `training_metadata` quotation marks must be escaped with a backslash `\`

**Comment by stevemart** [comment]
@proCoder02 you're missing a few things:

* curly brackets around `apikey`, so `apikey:{apikey}`
* need backslashes around the quotes in `training_metadata`
* missing the `/v1/classifiers` endpoint in your URL

```
curl -i -u "apikey:{YOUR_API_KEY}" -F training_data=@C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier\data\ICD-10-GT-AA.csv -F training_metadata="{\"language\":\"en\",\"name\":\"ICD_classifier\"}" "https://gateway-fra.watsonplatform.net/natural-language-classifier/api/v1/classifiers"
```

**Comment by proCoder02** [comment]
Thanks a lot!!! :) that issue was resolved and i was able to train my model but after few mins it showed me this error
{
"code" : 400,
  "error" : "Entitlement error",
  "description" : "This user or service instance has the maximum number of classifiers."
}

this is the complete note - I got this error after it start to train my model and showed a status="training"

but after wards i got this entitlement error

C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier>curl -i -u "apikey:#######################################################" -F training_data=@C:\Users\mohana.kalyan\Desktop\ibm3\nlc-icd10-classifier\data\ICD-10-GT-AA.csv -F training_metadata="{\"language\":\"en\",\"name\":\"ICD_classifier\"}" "https://gateway-fra.watsonplatform.net/natural-language-classifier/api/v1/classifiers"
HTTP/1.1 100 Continue
X-Note: Gateway Ack

HTTP/1.1 400 Bad Request
X-Backside-Transport: FAIL FAIL
Content-Type: application/json
X-XSS-Protection: 1
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store
Pragma: no-cache
Expires: 0
x-global-transaction-id: 683fc2df5c6a3f901b27a061
X-DP-Watson-Tran-ID: gateway-fra-dp01-455581793
X-DP-Transit-ID: gateway-fra-dp01-455581793
Strict-Transport-Security: max-age=31536000;
Content-Length: 121
Date: Mon, 18 Feb 2019 05:16:02 GMT
Connection: close

{
  "code" : 400,
  "error" : "Malformed data",
  "description" : "The 'text' value at line 1 and column 1 is 'empty'."
}


kindly resolve :) it would be of great help :)!!!

**Comment by stevemart** [comment]
Try deleting all the classifiers first, then recreate it again.

The API docs https://cloud.ibm.com/apidocs/natural-language-classifier#create-classifier will have the right syntax

**Comment by stevemart** [comment]
@proCoder02 I'm looking at this further and you've hit two different errors. The first (`401 Unauthorized`) is happening because you are wrapping the classifier IDs with `{ }`s, no need for that. Try running:

```
$ curl -u "apikey:{2cnR6681oiUV6qOQBcA4yqRUNJzLtq2aTO9R6TmvI-kT}" "https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers}/v1/classifiers/c33e1ex339-nlc-38"
```

The second error (`400 This user or service instance has the maximum number of classifiers`) is happening because you are attempting to create another classifier and you're on the free tier, which has a limit of one.

**Comment by proCoder02** [comment]
Thanks for resolving that error...
We're almost there...
It would be great if you help in solving this issue..

(mytestenv) (base) C:\Users\mohana.kalyan\Desktop\ibm5\nlc-icd10-classifier>python welcome1.py
Traceback (most recent call last):
  File "welcome1.py", line 43, in <module>
    NLC_SERVICE = NaturalLanguageClassifierV1()
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\watson_developer_cloud\natural_language_classifier_v1.py", line 89, in __init__
    use_vcap_services=True)
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\watson_developer_cloud\watson_service.py", line 275, in __init__
    'You must specify your IAM api key or username and password service '
ValueError: You must specify your IAM api key or username and password service credentials (Note: these are different from your Bluemix id)


Thanks again...!:)

**Comment by proCoder02** [comment]
FYI I have updated the .env file with my current active API key credentials and I have also trained my model and the test model is working fine on IBM Watson Cloud but when I try to run locally it shows this error.

**Comment by proCoder02** [comment]
We were able to resolve the above issue but then again its showing this error. And moreover we try to access the local host 5000 on the browser it shows an internal sever error.
![capture23](https://user-images.githubusercontent.com/21214465/53069522-4bd57d80-3502-11e9-85ce-c6e3eec3fcf0.PNG)
 


C:\Users\mohana.kalyan\Desktop\ibm5\nlc-icd10-classifier>python welcome45.py
yGXCJ9lTtugESSQit2tOm9KeUvTbY2troHQabB1MtDby
 * Serving Flask app "welcome45" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-02-20 11:23:09,271] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "welcome45.py", line 53, in Welcome
    CLASSIFIER = _create_classifier()
  File "welcome45.py", line 89, in _create_classifier
    result = NLC_SERVICE.list_classifiers().get_result()
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\watson_developer_cloud\natural_language_classifier_v1.py", line 293, in list_classifiers
    method='GET', url=url, headers=headers, accept_json=True)
  File "C:\Users\mohana.kalyan\mytestenv\lib\site-packages\watson_developer_cloud\watson_service.py", line 490, in request
    info=error_info, httpResponse=response)
watson_developer_cloud.watson_service.WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401 , X-dp-watson-tran-id: gateway02-2278045209 , X-global-transaction-id: ffea405d5c6ceb4587c83619
127.0.0.1 - - [20/Feb/2019 11:23:09] "GET / HTTP/1.1" 500 -

**Comment by proCoder02** [comment]
Kindly help us find a solution We are stuck :(

**Comment by stevemart** [comment]
@proCoder02 great to hear you got it working on our cloud.

The error indicates that the credentials are not correct. Can you paste you .env file? Remove or replace some of the characters in the api keys, please.

**Comment by proCoder02** [comment]
This is our .env file..


NATURAL_LANGUAGE_CLASSIFIER_USERNAME=<add_NLC_username>
NATURAL_LANGUAGE_CLASSIFIER_PASSWORD=<add_NLC_password>

NATURAL_LANGUAGE_CLASSIFIER_IAM_APIKEY=##############UvTbY2troHQabB1MtDby

**Comment by stevemart** [comment]
@proCoder02 remove the first two lines, the ones about username and password

**Comment by proCoder02** [comment]
Tried doing that..
Having the same issue...

**Comment by proCoder02** [comment]
Working fine 
Thank you....

**Comment by stevemart** [comment]
thanks for the heads up
